version: '2'

services:
  webserver-rphstudio-asteroid:
    image: registry.admin.rphstudio.net/rphstudio-asteroid
    networks:
      - webtraefik
    expose:
      - "80"
    labels:
      - "traefik.backend=webserver-rphstudio-asteroid"
      - "traefik.docker.network=webtraefik"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:asteroid.game.rphstudio.net"

networks:
  webtraefik:
    external: true